if [ -f "$HOME/.tool-versions" ]; then
  _go_ver=$(awk '/^golang/ {print $2}' "$HOME/.tool-versions")
  if [ -n "$_go_ver" ] && [ -d "$HOME/.asdf/installs/golang/$_go_ver/go" ]; then
    export GOROOT="$HOME/.asdf/installs/golang/$_go_ver/go"
    export PATH="$GOROOT/bin:$PATH"
  fi
  unset _go_ver
fi
