vim.keymap.set("n", "<C-h>", "<C-w><C-h>", { desc = "Move Focus Left" })
vim.keymap.set("n", "<C-j>", "<C-w><C-j>", { desc = "Move Focus Down" })
vim.keymap.set("n", "<C-k>", "<C-w><C-k>", { desc = "Move Focus Up" })
vim.keymap.set("n", "<C-l>", "<C-w><C-l>", { desc = "Move Focus Right" })
vim.keymap.set("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear Search Highlight" })
vim.keymap.set("t", "<Esc><Esc>", "<C-\\><C-n>", { desc = "Exit Terminal Mode" })
vim.keymap.set("t", "ii", "<C-\\><C-n>", { desc = "Exit Terminal Mode" })
vim.keymap.set("i", "ii", "<Esc>")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<leader>in", "<cmd>tabnew<cr>", { desc = "[N]ew Tab" })
vim.keymap.set("n", "<leader>ic", "<cmd>tabclose<cr>", { desc = "[C]lose Tab" })
vim.keymap.set("n", "<leader>io", "<cmd>tabonly<cr>", { desc = "Close [O]ther Tabs" })
vim.keymap.set("i", "<C-Tab>", vim.snippet.jump)
vim.keymap.del("i", "<Tab>")

-- [T]oggle
vim.keymap.set("n", "<leader>tw", function()
	vim.opt.wrap = not vim.opt.wrap:get()
end, { desc = "Toggle [W]rap" })
vim.keymap.set("n", "<leader>tl", function()
	vim.opt.relativenumber = not vim.opt.relativenumber:get()
end, { desc = "Toggle Relative [L]ine Numbers" })
vim.keymap.set("n", "<leader>ts", function()
	vim.opt.spell = not vim.opt.spell:get()
end, { desc = "Toggle [S]pell" })
vim.keymap.set("n", "<leader>td", function()
	vim.diagnostic.enable(not vim.diagnostic.is_enabled())
end, { desc = "Toggle [D]iagnostics" })
vim.keymap.set("n", "<leader>tv", function()
	local cfg = vim.diagnostic.config()
	if cfg.virtual_lines then
		vim.diagnostic.config({ virtual_lines = false, virtual_text = true })
	else
		vim.diagnostic.config({ virtual_lines = true, virtual_text = false })
	end
end, { desc = "Toggle Diagnostic [V]irtual Lines" })
vim.keymap.set("n", "<leader>tb", "<cmd>Gitsigns toggle_current_line_blame<cr>", { desc = "Toggle Git [B]lame" })
