[services]
gog = True
egs = True
ea_app = True
ubisoft = True
steam = True

[lutris]
library_ignores = 
migration_version = 17
icon_type_gridview_egs = game_banner_small
width = 1659
height = 885
window_x = 45
window_y = 45
maximized = False
icon_type_gridview_steam = banner
icon_type_gridview = coverart_med
filter_installed = True
show_advanced_options = False
selected_category = platform:Windows

